### ISSUE TITLE
Feature Request: Add DCSync to ntlmrelayx.py

### ISSUE THREAD

**Issue by Thanathan-k** [SecureAuthCorp/impacket#1107]
It would be great to have the option to use DCSync with ntlmrelayx.py in case we are able to catch and relay a user with the corresponding rights.

**Comment by ShutdownRepo** [comment]
I think ntlmrelayx already offers this feature. Try something like `ntlmrelayx.py dcsync://domain_controller`.
cf. https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/attacks/dcsyncattack.py

**Comment by 0xdeaddood** [comment]
Hi @Thanathan-k! 

If the DC is vulnerable to zerologon, you can use the dcsync relay client as @ShutdownRepo mentioned. With `ntlmrelayx.py -t DCSYNC://domain_controler -smb2support` you will dump the krbtgt, DC$ and Administrator accounts (that's because the attack implementation uses a TCP connection instead of SMB one). 

If you have the credentials of a low-privilege account, you can connect over SMB and obtain all the hashes: `ntlmrelayx.py -t DCSYNC://domain_controler -smb2support -auth-smb domain/low_priv_user:password`

For more details, you can check [this blog post](https://dirkjanm.io/a-different-way-of-abusing-zerologon/
) from @dirkjanm.

**Comment by Thanathan-k** [comment]
Hey. Thanks for your answers @ShutdownRepo and @0xdeaddood. However I knew of these functionalities already. I'm talking about a situation where a domain controller has no signing enforced, and I am able to trigger an authentication of one of the domain controllers to myself (for example with dementor/the printer bug). In this case the domain controller account should have DCSync rights. Since secretsdump is able to exploit this right (see earlier exploits with the exchange servers and granting a user DCSync rights using -escalate-user and afterwards using secretsdump to get the password hashes) I guess it should also be possible to directly use this functionality of secretsdump within ntlmrelayx instead of trying to dump the local hashes, therefore not requiring administrative privileges.

I've already tried myself to implement it and will continue to do so, however people already familiar with the code might get it done faster, so I thought asking here couldn't hurt :)

**Comment by dirkjanm** [comment]
DCSync uses DRSUAPI which always requires signing (not configurable unlike SMB signing), so unless you have the actual password of the account or the server is vulnerable to zerologon, you can't relay to it.

**Comment by Thanathan-k** [comment]
@dirkjanm Thank you for the information! I wasn't aware of that. Seems like I should have delved deeper into the protocols, instead of only trying to figure out the impacket code.

Closing the issue then.
