### ISSUE TITLE
Ntlmrelayx - can't modify commands run with "-c" option?

### ISSUE THREAD

**Issue by braimee** [SecureAuthCorp/impacket#1115]
Hello,

I'm trying to run ntlmrelayx with the `-c` option to do a `net group` command.  It was failing on the target box, so to try and figure it out, I put ntlmrelayx into `debug` mode and also broke the command down step by step at the server 2019 box in my lab.

On the ntlmrelayx side, what's being run is:

`
ExecuteRemote command: %COMSPEC% /Q /c echo my command here ^> %SYSTEMROOT%\Temp\__output > %TEMP%\execute.bat & %COMSPEC% /Q /c %TEMP%\execute.bat & del %TEMP%\execute.bat
`

However, when I run this manually on the server 2019 box, the `__output` does *not* get echoed to `execute.bat` unless I add another `^` right after `%SYSTEMROOT%\Temp\__output` and before the `%TEMP%\execute.bat`.  

So the full (working) command on my test server is:

`%COMSPEC% /Q /c echo net group "Domain Admins" someguy /add /domain ^> %SYSTEMROOT%\Temp\__output ^> %TEMP%\execute.bat & %COMSPEC% /Q /c %TEMP%\execute.bat & del %TEMP%\execute.bat`

It seems like it should be easy enough for me to find where the `__output` strings are in the tools and change it to `__output ^`.  I've done that everywhere I can find, and even tried changing `execute.bat` to be `meow.bat` in various files to see if that gets reflected in the tool output, but none of those values seem to be updating.

Can you please help me as I think I'm missing something right in front of me?

Thanks,
Brian

**Comment by braimee** [comment]
Update: if I run ntlmrelayx with SOCKS and capture a session that way, I'm able to modify values in smbexec.py (like changing batch file name, changing %comspec% to something else, etc.) and those values WORK when I fire smbexec.py.

But I can't figure out what file/variables ntlmrelayx looks to when I run it with `-c`.  I feel close, yet so far!

**Comment by 0xdeaddood** [comment]
Hi @braimee! I'm trying to understand your issue. You are relaying to SMB, to a Windows Server 2019, and trying to execute a `net group` command with the -c option. I have some points to check with you:

- I suppose you disabled the SMB signing (enable by default in Windows Server machines), didn't you? Otherwise the attack wouldn't work. 

- What is the full command line you are using? I ran the following one against a Windows Server 2019 with SMB signing disabled and it worked: ` ntlmrelayx.py -t xxx.xxx.xxx.xxx -c "net group \"Domain Admins\" user /add /domain" -smb2support`

Finally, if you need to modify something from the code here is the function: https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/secretsdump.py#L928

**Comment by braimee** [comment]
Hello @0xdeaddood thanks for the response and sorry for the delay.  I think we can close this for now as the engagement I was working on is over.  I'll have more tests coming in following weeks and can comment again if/when I can recreate this.  Thanks again for the help.
