### ISSUE TITLE
MS KRB5 - Microsoft Kerberos 5 incompatibility

### ISSUE THREAD

**Issue by arthdzn** [SecureAuthCorp/impacket#1215]
### Configuration  
impacket version:  0.9.25
Python version:  3.7.3
Target OS:  Debian 10

### Debug Output With Command String  
_Unsupported MechType 'MS KRB5 - Microsoft Kerberos 5_
![image](https://user-images.githubusercontent.com/94058037/143012656-af602b6f-ac45-4808-adfb-259a92310fe2.png)

### Additional context  
The smb server has a computer account in my Active Directory & the problem occurs when there is a request to the server with the DNS name related to the domain
Thanks for your help

**Comment by dirkjanm** [comment]
What exactly is the bug here? When the client connects to the SMB server that you're hosting it will send Kerberos authentication by default. Since smbserver.py is NTLM only it can't do anything with the Kerberos auth so it will give you that message. Then the client will fallback to NTLM and it works as expected.

**Comment by 0xdeaddood** [comment]
Hi @arthdzn! As @dirkjanm mentioned, the SMB server doesn't support Kerberos authentication. Closing.
