### ISSUE TITLE
socket.gaierror: [Errno -2] Name

### ISSUE THREAD

**Issue by SrStrock** [SecureAuthCorp/impacket#1242]
`python3 mssqlclient.py ARCHETYPE/sql_svc@{TARGET_IP} -windows-auth`
When I put this command from a starting point hack the box machine, it drops the error "socket.gaierror: [Errno -2] Name".
I've put the password correctly and I don't know anything else to do. There are no writing mistakes.

**Comment by 0xdeaddood** [comment]
Hi @SrStrock!

A `socket.gaierror` is an exception raised for address-related errors. Are you defining an `IP address` as the target? If so, please check that you are setting a valid address. If you are defining a `hostname`, the error is related to the name resolution system (check your DNS configurations).

**Comment by SrStrock** [comment]
Yes, as I am doing a HTB machine, im trying to access to an IP adress, i've tried with diferent IPs resetting the machine and it didn't work.

**Comment by Agesilaos** [comment]
you just have to use this command
`python3 mssqlclient.py ARCHETYPE/sql_svc@XX.XXX.XXX.XX -windows-auth`
insted of this command
`python3 mssqlclient.py ARCHETYPE/sql_svc@{TARGET_IP} -windows-auth`
The error `socket.gaierror: [Errno -2] Name` is given because your using `{}` and for specify a `ip address` you just have to put the ip address after `aql_svc@`

**Comment by 0xdeaddood** [comment]
Hey @SrStrock!

Have you solved this? As @Agesilaos mentioned, you have to set an IP address without `{}`.

**Comment by SrStrock** [comment]
its done, thank you :)))
