### ISSUE TITLE
wmiquery fails when executed from a FIPS system

### ISSUE THREAD

**Issue by AndyPigPenDoran** [SecureAuthCorp/impacket#1246]
```
# python wmiquery.py <DOMAIN>/<USER>:<PASSWORD@<TARGET>
Impacket v0.9.24 - Copyright 2021 SecureAuth Corporation

[-] error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
```

If I run the same from a non-FIPS system, there is no issue. Is there a way to become FIPS compliant?

**Comment by AndyPigPenDoran** [comment]
btw - this happens at the dcom.CoCreateInstance call:

`iInterface = dcom.CoCreateInstanceEx(wmi.CLSID_WbemLevel1Login,wmi.IID_IWbemLevel1Login)`

**Comment by martingalloar** [comment]
Hey Andy!

I think there're two different items:
1) Become FIPS-compliant would mean that we'll have to only use cryptographic algorithms that are approved and implementations that are FIPS-compliant.
2) Become FIPS-compatible, in the sense that the library would work on systems that have FIPS-compliant cryptographic libraries installed (e.g. system-wide `OpenSSL`).

I guess you meant 2), right? In the case of `wmiquery.py` it's probably failing at creating the DCOM interface and trying to authenticate the connection, but without a full stack trace not sure what particular algorithm is disabled in that system. (maybe `hashlib.md5`? 🤔)

Impacket relies directly on two main cryptographic libraries (`pyCryptoDomeEx` and `pyOpenSSL`) and indirectly also on cryptography. Going after 1) would mean that we'll need to switch to (or be compatible with) a FIPS-compliant version of one of those, and that non-approved algorithms are disabled (ej. `MD4`/`MD5`), which would probably break a good amount of functionality. Pursuing 2) would mean that either we disable non-approved algorithms (and break a good amount of functionality) or we switch to native implementations of those algorithms instead of relying on `OpenSSL`.

1) is definitely not under out roadmap, but even 2) it's a big undertaking with a very large impact IMHO.

**Comment by AndyPigPenDoran** [comment]
Hi.. thanks for the response... I guess that yes - #2 is what I am looking at. Basically we have been using wmic to get WMI query results, but that breaks on connecting to Windows 2020. There is an update (1.4) to that which works, but there are DCOM security updates coming from Microsoft and it does not work when those are enabled.

I have been looking at changing to Impacket and it's been working perfectly so far. But we have FIPS enabled systems as well as non FIPS. It's not working on the FIPS enabled systems.

I managed to find that it is here in ntlm.py that it generates the error:

```
def hmac_md5(key, data):
    import hmac
    h = hmac.new(key, digestmod=hashlib.md5)
    h.update(data)
    return h.digest()
```
    
A quick test shows that this fails with the error:
  
```
import hashlib

c = hashlib.md5()
```

But this works without any problem:

```
import hashlib

c = hashlib.md5(usedforsecurity=False)

```

I  guess it's rather more complicated than that to make a similar change in Impacket, and it probably has a wider implication if that's done. I was hoping there might be an answer along the lines of "yeah - just use this switch"... ;^)

**Comment by AndyPigPenDoran** [comment]
I had a look at changing from md5 to sha1 (wherever md5 is used)... but now get "access denied" when the connection is establised (or tries to be established). I guess there's more to it than that...

**Comment by jagotu** [comment]
If the protocol expects MD5 hashes, you can't just send SHA1 hashes instead and expect stuff to work.

If providing `usedforsecurity=False` to hashlib constructors is really all that's necessary to make it work on FIPS, you should be able to patch the hmac calculation like this:

```
def hmac_md5(key, data):
    import hmac
    h = hmac.new(key, digestmod=lambda : hashlib.md5(usedforsecurity=False))
    h.update(data)
    return h.digest()
```

**Comment by AndyPigPenDoran** [comment]
Thanks for that - this now works... so if I change everywhere in ntlm.py that uses md5 (ie haslib.new('md5') ) and use your code above for the hmac_md5 ... I can now connect and get data back from Windows servers when running from a Linux system with FIPS enabled (and still works with a system where FIPS is not enabled).

I guess the question then becomes "does that break the rules for FIPS"? The general idea would be (quoted from someone else)

"if a protocol uses md5 in generating handshake nonces or checking integrity of wire traffic, then fips-enabled systems must not use that protocol"

If by changing to use usedforsecurity, I am doing that - then it's not going to be approved. But if not then it should be OK.

So it works, but I'm not sure if that's against the rules. Makes me wonder how wmic does things since that does work on FIPS enabled systems.

**Comment by jagotu** [comment]
Such an assessment is way beyond what I'm comfortable with giving an answer to, given I have no idea about FIPS. I just provided a technical solution to feeding the flag during HMAC generation.

**Comment by AndyPigPenDoran** [comment]
That's OK - I didn;t mean to suggest I was asking you to commit to answering that question... that's beyond my scope too. I'm grateful for your help on the technical question... as a PoC it shows that this can work on FIPS enabled systems which was the initial goal. Now I need to see what the security folks think.... ;^)

**Comment by martingalloar** [comment]
Closing this one for now. Feel free to reopen if you've any further question, and report back if you needed to perform any other patch to make it work ;)
