### ISSUE TITLE
Capturing command success/failure within wmiexec.py or wmiquery.py

### ISSUE THREAD

**Issue by tlathm** [SecureAuthCorp/impacket#323]
I'm trying to determine if there is, or could be, some means of determining when a single command run via the onecmd() call succeeded or failed from within calling code such as the wmiexec.py and wmiquery.py examples. That it, when a command fails, I'd like to be able to exit the script with a non-zero status.

For example, the wmiquery.py has:
``                shell.onecmd(line)``
In that case, some errors, for example an invalid namespace, raise an exception that can be caught in the script. However others such as an invalid class, log errors from somewhere deep in other code, but the calling script isn't really aware of them.

Similarly, wmiexec.py has the line:
``                self.shell.onecmd(self.__command)``
Unless something in the underlying call raises an exception that gets caught in the script, the calling code has no idea if self.__command actually succeeded. That is for example...it's return code. In that case however even debug logging doesn't indicate when a command failed, and I'm not sure if anything is aware of the remote command exit status.

**Comment by asolino** [comment]
Hey @tlathm 

`wmiquery.py`: There are two places where exceptions are triggered:
1. The Initial DCOM Connection, Remote Interface Instantiation and connection to a WMI Namespace. If something fails it will be processed [here](https://github.com/CoreSecurity/impacket/blob/master/examples/wmiquery.py#L207). This type of error is fatal, meaning the script must stop.
2. Once the connection is active, there could be other errors (such like invalid class, invalid query, etc) that are *not* fatal (meaning the script can continue), that's why they are caught somewhere else inside the code, specifically [here](https://github.com/CoreSecurity/impacket/blob/master/examples/wmiquery.py#L110). The case of `shell.onecmd()` has the same behaviour.. Ends in the same code.

If you're trying to catch errors in the output of this script I see two options:
1. Search for the `[-] WMI Session Error` text and act accordingly.
2. Modify this example script so every time an error is triggered, exit the script with the error code thrown by WMI. You can get the error code using the `get_error_code()` method of the exception thrown. For example, if you just `raise` the exception thrown [here](https://github.com/CoreSecurity/impacket/blob/master/examples/wmiquery.py#L111) (replace that line with `raise`) and then you `exit` the script with the error code received (insert in [this](https://github.com/CoreSecurity/impacket/blob/master/examples/wmiquery.py#L213) line `sys.exit(e.get_error_code()` indented inside the Exception) I think you might be able to achieve what you want too. Haven't tested it tho.. and a hindrance you might have is windows errors are big numbers that I don't know if `sys.exit()` supports that.

`wmiexec.py`: The functionality is kind of similar as explained before, but there's a big difference. That script executes WMI [Win32_Process.Create()](https://msdn.microsoft.com/en-us/library/aa389388(v=vs.85).aspx) always calling `CMD.EXE` as the shell (see [here](https://github.com/CoreSecurity/impacket/blob/master/examples/wmiexec.py#L115)). That means there won't be errors in the main's program execution, making it harder to get the error whatever you executed. I'm sure there could be other ways to achieve what you need, and more research is needed and definitely outside the scope of this script. But, since you have everything in Python the idea for users is to customize these scripts based on their needs.

hope this helps.

**Comment by tlathm** [comment]
Thanks a million! That gives me a lot to look into.

**Comment by tlathm** [comment]
Awesome. Your explanation of the wmiquery.py got me on the right track. I already had a change to handle the fatal errors, and for the other non-fatal errors, all I needed to do was to re-raise the exception in that default function.

I can see where the wmiexec.py stuff could get a lot trickier. Thanks again!

**Comment by tlathm** [comment]
Wow. I wish I could say I didn't feel light years out of my league, but wherever I might be able to get anything resembling the return status' of commands run in wmiexec.py seems to be buried way to far for me to find. I thought I was close when I discovered that the self.__win32Process.Create call in the RemoteShell class within execute_remote returned an impacket.dcerpc.v5.dcom.wmi.IWbemClassObject instance that actually had a ReturnValue property. However that appears to be zero even for failed commands.

Tough one for sure. Unfortunately for us, being able to run remote commands without knowing if they worked doesn't really help. Will keep digging.

**Comment by asolino** [comment]
Hey @tlathm 

Nobody said WMI is easy ;).. did you execute with or without the `cmd.exe /c` prefix?.. If you do that, regardless of what you exectute later, the return code will always be zero because `cmd.exe` was successfully created. 
Thinking out loud.. did you try executing remote commands thru WinRS? (e.g. pywinrm). That could also be helpful.

**Comment by tlathm** [comment]
Yea...I didn't expect anything remotely related to Windows in general to be easy. I'm not sure I want to pursue the pywinrm as yet, only because we need to access older systems.

You're suggestion regarding omitting the cmd.exe prefix sounds promising though...I was in fact still using that. I'll have to take a look at that. Thanks!

**Comment by tlathm** [comment]
Pardon my ignorance if I'm missing something (or perhaps a lot of things) here: It appears that removing the cmd /c from the command turns into somewhat of a rewrite of what's going on there. Isn't the shell that's being created itself effectively running cmd as it stands now? At a minimum obviously none of the do_cd stuff would apply if the process is created for the command directly. I think I'm just having a tough time differentiating between the shell interpreter there and the win32process that it's using.

**Comment by asolino** [comment]
It is definitelly a rewrite. Instead of executing commands through `cmd /c` you will be creating processes directly with the executable you want to execute (e.g. notepad).
Forget about the `do_cd/get/put/lcd` you should remove all that.

Maybe, since you're testing whether WMI could be a solution for you, you can do all these tests from  Visual Basic, or PowerShell.. check this link, it might be useful: https://msdn.microsoft.com/en-us/library/aa389388(v=vs.85).aspx

**Comment by tlathm** [comment]
Thanks for confirming that! I think that the psexec.py will most likely be our best approach to tell you the truth...though that status 1 failure on longer commands is still a mystery. I might get a friend who's a very knowledgable Windows programmer to look at that one.

**Comment by tlathm** [comment]
For reasons almost too painful to go into I've been revisiting this one again: Quick question. I see that the existing wmiexec.py script gets the command output by redirecting it to the file defined in the __output property and then apparently reading from that. It occurs to me that the means currently used there to do that...that is redirecting to the file...obviously can't work in the absence of the cmd.exe shell. Are there any other means by which to get the output of a command run directly? I'm assuming that, if so, it would be quite involved. Thanks!

**Comment by asolino** [comment]
Hey... Indeed wmiexec.py grabs the output from the `__output` file and it won't work without calling `cmd.exe` first. Honestly, don't know about other ways to grab the output from a WMI CreateProcess.

**Comment by tlathm** [comment]
Thanks! I sort of figured as much. In a pinch we can probably do something with the underlying command within cmd.exe like (<command> || ECHO SOME_RECOGNIZABLE_STRING) and look for that in the output.

**Comment by qixinwuchen** [comment]
Has your problem been solved？  I need to know the return status code of the command execution, 0 or 1.     thanks
