### ISSUE TITLE
problems with relaying to ldap/ldaps

### ISSUE THREAD

**Issue by thisiseast** [SecureAuthCorp/impacket#544]
Hi sir, I've been testing NTLM Relay with ldap and got some problem
1. **./ntlmrelayx.py -t ldap://asdfsd.kkk.com**
the code got stuck at line 112 in `impacket.examples.ntlmrelayx.clients.ldaprelayclient.LDAPRelayClient#sendAuth` 
show below:
![image](https://user-images.githubusercontent.com/15681287/49923672-34b95480-feef-11e8-870b-76fb84dd09ba.png)

what's observed in traffic with Wireshark is:
![image](https://user-images.githubusercontent.com/15681287/49924360-0b99c380-fef1-11e8-9be6-9b064b31ae54.png)

from the picture above authentication was seemingly successful but operation failed to proceed.

2.   **./ntlmrelayx.py -t ldaps://asdfsd.kkk.com**
authenticaion failure was observed despite the credential being accurate.
[ * ] Servers started, waiting for connections
[ * ] SMBD: Received connection from 192.168.0.4, attacking target ldaps://asdfsd.kkk.com
testtest
[ - ] Authenticating against ldaps://asdfsd.kkk.com as KKK\Administrator FAILED

It's confirmed by looking at  the registry that there is neither ldaps channel binding or ldap signing in effect. Could you please help me with this?

**Comment by asolino** [comment]
Thanks for reporting the issue @thisiseast .

@dirkjanm, any idea of this behavior?

**Comment by dirkjanm** [comment]
You are relaying from SMB to LDAP, which does not work since the protocols are not relay-compatible. This is further discussed in #500 
This should probably be documented better or indicated by ntlmrelayx because right now it is just erroring out without saying why.

This is what is happening in your two scenarios:
1. The authentication is successful, but because of the NTLM flags set the LDAP server expects a signed LDAP message. The message sent by ntlmrelayx is not signed (we don't have the signing keys since we are relaying), and thus the server ignores the message and the code hangs.
2. The authentication is not successful, because the NTLM flags indicate that signing is requested, which is not supported for LDAP over TLS/SSL (LDAPS). If you run in verbose/debug mode I believe it will show the message from the server telling you this.

Hope this clears it up :)

**Comment by asolino** [comment]
It does, thanks @dirkjanm 

I'm leaving this open. We should clarify it during the execution. If we don't know where the original relay comes from (e.g. HTTP or SMB) at least output a Warning message.
