### ISSUE TITLE
Feature request: adding a getNTLMSSPType2 high level function to ntlm.py

### ISSUE THREAD

**Issue by lean0x2F** [SecureAuthCorp/impacket#567]
Hi! While crafting a HTTP Mock server with NTLM support I realized I had no simple and generic way to create a NTLM Type 2 response. Type 1 and Type 3 are both implemented in a high-level fashion in getNTLMSSPType1 and getNTLMSSPType3 in ntlm.py.

Searching for some code to reuse I found "smbserver.py" that implements a NTLM_CHALLENGE response. 

I came up with this code:

```python
    def getNTLMSSPType2(type1, hostname, domain, fqdn, dnsdomain, random_challenge=True):

        # Get NTLM_NEGOTIATE structure
        negotiate_message = ntlm.NTLMAuthNegotiate()
        negotiate_message.fromString(type1)

        # Generate the AV_PAIRS
        av_pairs = ntlm.AV_PAIRS()
        av_pairs[ntlm.NTLMSSP_AV_HOSTNAME] = hostname.encode('utf-16le')
        av_pairs[ntlm.NTLMSSP_AV_DNS_HOSTNAME] = fqdn.encode('utf-16le')
        av_pairs[ntlm.NTLMSSP_AV_DOMAINNAME] = domain.encode('utf-16le')
        av_pairs[ntlm.NTLMSSP_AV_DNS_DOMAINNAME] = dnsdomain.encode('utf-16le')
        av_pairs[ntlm.NTLMSSP_AV_TIME] = struct.pack('<q',
                                                     (116444736000000000 + calendar.timegm(time.gmtime()) * 10000000))

        # Let's build the answer flags
        response_flags = 0

        if negotiate_message['flags'] & ntlm.NTLMSSP_NEGOTIATE_UNICODE:
            response_flags |= ntlm.NTLMSSP_NEGOTIATE_UNICODE
        if negotiate_message['flags'] & ntlm.NTLM_NEGOTIATE_OEM:
            response_flags |= ntlm.NTLM_NEGOTIATE_OEM
        if negotiate_message['flags'] & ntlm.NTLMSSP_NEGOTIATE_56:
            response_flags |= ntlm.NTLMSSP_NEGOTIATE_56
        if negotiate_message['flags'] & ntlm.NTLMSSP_NEGOTIATE_128:
            response_flags |= ntlm.NTLMSSP_NEGOTIATE_128
        if negotiate_message['flags'] & ntlm.NTLMSSP_NEGOTIATE_KEY_EXCH:
            response_flags |= ntlm.NTLMSSP_NEGOTIATE_KEY_EXCH
        if negotiate_message['flags'] & ntlm.NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY:
            response_flags |= ntlm.NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY

        response_flags |= ntlm.NTLMSSP_NEGOTIATE_VERSION | ntlm.NTLMSSP_NEGOTIATE_TARGET_INFO | ntlm.NTLMSSP_TARGET_TYPE_SERVER | ntlm.NTLMSSP_NEGOTIATE_NTLM | ntlm.NTLMSSP_REQUEST_TARGET

        # Let's build the NTLM_CHALLENGE message
        challenge_message = ntlm.NTLMAuthChallenge()
        challenge_message['flags'] = response_flags
        challenge_message['domain_len'] = len(domain.encode('utf-16le'))
        challenge_message['domain_max_len'] = challenge_message['domain_len']
        challenge_message['domain_offset'] = 40 + 16
        challenge_message['challenge'] = str(os.urandom(8)) if random_challenge else '\x11\x22\x33\x44\x55\x66\x77\x88'
        challenge_message['domain_name'] = domain.encode('utf-16le')
        challenge_message['TargetInfoFields_len'] = len(av_pairs)
        challenge_message['TargetInfoFields_max_len'] = len(av_pairs)
        challenge_message['TargetInfoFields'] = av_pairs
        challenge_message['TargetInfoFields_offset'] = 40 + 16 + len(challenge_message['domain_name'])
        challenge_message['Version'] = '\xff' * 8
        challenge_message['VersionLen'] = 8

        return challenge_message

```

I really don't know if this code is suitable for all situations. Some things that come to my mind are:

- Lack of signing. What should happen if we receive NTLMSSP_NEGOTIATE_SIGN & NTLMSSP_NEGOTIATE_SEAL? should we drop the connection, do nothing, or do we have some way to support signing on impacket?
- What about NTLMSSP_NEGOTIATE_ALWAYS_SIGN? Can we just ignore it if we receive it?
- Which av_pairs are completely necessary? For example, I've seen NTLMSSP_AV_DNS_TREENAME is being set by some servers, but the examples I've seen on Impacket lack that one. 

Thanks :)

**Comment by asolino** [comment]
Hola @lean0x2F!

Thanks for bringing this up.. Actually never thought about coding a generic function for Type2 responses calls. I'm sure it you need it for an specific use case :)
I guess your code should be enough, I would add the possibility of specifying a particular challenge (useful for password cracking) but then we will need to test it live. Type2 responses usually depend on the server configuration, so that's why I never made it generic (I any case, there's no reason not to pick a default value and go for it. That's what I did for `getNTLMSSPType1`).

> Lack of signing. What should happen if we receive NTLMSSP_NEGOTIATE_SIGN & NTLMSSP_NEGOTIATE_SEAL? should we drop the connection, do nothing, or do we have some way to support signing on impacket?

Signing **is** supported in impacket, both at the clients (for quite some time now) and the `smbserver.py` (check [this](https://github.com/SecureAuthCorp/impacket/commit/b579cfc6e1ddca43f64c0adb1e434d1006cc612b) commit for the server part). Have in mind the decision to sign or not to sign for SMB is outside these blobs (check [here](https://github.com/SecureAuthCorp/impacket/blob/master/impacket/smb3.py#L638) for example).

> What about NTLMSSP_NEGOTIATE_ALWAYS_SIGN? Can we just ignore it if we receive it?

I think you can safely ignore it for SMB connections

> Which av_pairs are completely necessary? For example, I've seen NTLMSSP_AV_DNS_TREENAME is being set by some servers, but the examples I've seen on Impacket lack that one.

This I can't remember, you should take another look at [[MS-NLMP]](https://msdn.microsoft.com/en-us/library/cc236621.aspx) and do some research there. I would leave the ones I'm adding in the `smbserver.py` example. Seems to work well with many different OS versions.

Once you have something, you'd better issue a PR 👍
