### ISSUE TITLE
mssqlclient.py and Windows Authentication

### ISSUE THREAD

**Issue by ossie-git** [SecureAuthCorp/impacket#613]
When trying to log in from a Linux machine using Windows Authentication, it fails as shown below:

```
# mssqlclient.py -p 1433 EXAMPLE\Administrator@DC01 -windows-auth
Impacket v0.9.20-dev - Copyright 2019 SecureAuth Corporation

Password:
[*] Encryption required, switching to TLS
[-] ERROR(DC01\SQLEXPRESS): Line 1: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.
```

However, it is successful from a domain-joined client machine as shown below::

```
(impacketenv) C:\Python37-32\impacketenv\impacket\build\scripts-3.7\python mssqlclient.py Administrator@DC01 -windows-auth
Impacket v0.9.20-dev - Copyright 2019 SecureAuth Corporation

Password:
[*] Encryption required, switching to TLS
[*] ENVCHANGE(DATABASE): Old Value: master, New Value: master
[*] ENVCHANGE(LANGUAGE): Old Value: , New Value: us_english
[*] ENVCHANGE(PACKETSIZE): Old Value: 4096, New Value: 16192
[*] INFO(DC01\SQLEXPRESS): Line 1: Changed database context to 'master'.
[*] INFO(DC01\SQLEXPRESS): Line 1: Changed language setting to us_english.
[*] ACK: Result: 1 - Microsoft SQL Server   (120 7208)
[!] Press help for extra shell commands
```

Is there any way to get this working on non-domain joined machines or Linux clients?  If not, might it be better to have it detect the client OS and just print out that mssqlclient.py does not work with windows-auth on this platform?  Thanks.

PS.  I'm using the latest version (git clone)

**Comment by asolino** [comment]
Hey @ossie-git 

Impacket grabs nothing from a client machine in order to perform a MSSQL login. So, it shouldn't matter whether you're connecting from a Linux or Windows domain-joined machine. 
If it is failing that's because there is another reason (or a bug).

I'm seeing you calling the script different tho:
```
mssqlclient.py -p 1433 EXAMPLE\Administrator@DC01 -windows-auth
```
and 
```
mssqlclient.py Administrator@DC01 -windows-auth
```

try calling them both in the same way and let me know.

**Comment by asolino** [comment]
any updates here @ossie-git ?

**Comment by ossie-git** [comment]
You were right.  When using this syntax on my Linux box, it worked:

```
$ mssqlclient.py -p 1433 Administrator@DC01 -windows-auth
Impacket v0.9.20-dev - Copyright 2019 SecureAuth Corporation

Password:
[*] Encryption required, switching to TLS
[*] ENVCHANGE(DATABASE): Old Value: master, New Value: master
[*] ENVCHANGE(LANGUAGE): Old Value: None, New Value: us_english
[*] ENVCHANGE(PACKETSIZE): Old Value: 4096, New Value: 16192
[*] INFO(DC01\SQLEXPRESS): Line 1: Changed database context to 'master'.
[*] INFO(DC01\SQLEXPRESS): Line 1: Changed language setting to us_english.
[*] ACK: Result: 1 - Microsoft SQL Server (120 7208) 
[!] Press help for extra shell commands
SQL> 
```

**Comment by asolino** [comment]
Thanks for the clarification @ossie-git, closing this issue.

**Comment by gauravjumbo** [comment]
> When trying to log in from a Linux machine using Windows Authentication, it fails as shown below:
> 
> ```
> # mssqlclient.py -p 1433 EXAMPLE\Administrator@DC01 -windows-auth
> Impacket v0.9.20-dev - Copyright 2019 SecureAuth Corporation
> 
> Password:
> [*] Encryption required, switching to TLS
> [-] ERROR(DC01\SQLEXPRESS): Line 1: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.
> ```
> 
> However, it is successful from a domain-joined client machine as shown below::
> 
> ```
> (impacketenv) C:\Python37-32\impacketenv\impacket\build\scripts-3.7\python mssqlclient.py Administrator@DC01 -windows-auth
> Impacket v0.9.20-dev - Copyright 2019 SecureAuth Corporation
> 
> Password:
> [*] Encryption required, switching to TLS
> [*] ENVCHANGE(DATABASE): Old Value: master, New Value: master
> [*] ENVCHANGE(LANGUAGE): Old Value: , New Value: us_english
> [*] ENVCHANGE(PACKETSIZE): Old Value: 4096, New Value: 16192
> [*] INFO(DC01\SQLEXPRESS): Line 1: Changed database context to 'master'.
> [*] INFO(DC01\SQLEXPRESS): Line 1: Changed language setting to us_english.
> [*] ACK: Result: 1 - Microsoft SQL Server   (120 7208)
> [!] Press help for extra shell commands
> ```
> 
> Is there any way to get this working on non-domain joined machines or Linux clients? If not, might it be better to have it detect the client OS and just print out that mssqlclient.py does not work with windows-auth on this platform? Thanks.
> 
> PS. I'm using the latest version (git clone)

Resolution:
Instead of
# mssqlclient.py -p 1433 EXAMPLE\Administrator@DC01 -windows-auth
you can use
# mssqlclient.py -p 1433 EXAMPLE/Administrator@DC01 -windows-auth
(forward slash instead of back slash)

this too will resolve the issue.

with backslash ' \ '
`root@localhost:~# python3 /usr/share/doc/python3-impacket/examples/mssqlclient.py ARCHETYPE\sql_svc:M3g4c0rp123@10.10.10.27 -windows-auth
Impacket v0.9.21 - Copyright 2020 SecureAuth Corporation

[*] Encryption required, switching to TLS
[-] ERROR(ARCHETYPE): Line 1: Login failed for user 'ARCHETYPE\Guest'.`

with forward slash ' / '
`root@localhost:~# python3 /usr/share/doc/python3-impacket/examples/mssqlclient.py ARCHETYPE/sql_svc:M3g4c0rp123@10.10.10.27 -windows-auth
Impacket v0.9.21 - Copyright 2020 SecureAuth Corporation

[*] Encryption required, switching to TLS
[*] ENVCHANGE(DATABASE): Old Value: master, New Value: master
[*] ENVCHANGE(LANGUAGE): Old Value: , New Value: us_english
[*] ENVCHANGE(PACKETSIZE): Old Value: 4096, New Value: 16192
[*] INFO(ARCHETYPE): Line 1: Changed database context to 'master'.
[*] INFO(ARCHETYPE): Line 1: Changed language setting to us_english.
[*] ACK: Result: 1 - Microsoft SQL Server (140 3232) 
[!] Press help for extra shell commands
SQL> 
`

**Comment by prokunal** [comment]
I am getting this error in from linux machine, i tried all the method mentioned above, but nothing is working.

Password:
[*] Encryption required, switching to TLS
[-] ('unpack requires a buffer of 1 bytes', "When unpacking field 'Type | <B | b''[:1]'")

**Comment by DDL08** [comment]
![Image](https://github.com/user-attachments/assets/9e538ae7-cb91-4e2e-82dc-d638a6cf0470?raw=true)I also encountered this problem

**Comment by Ya1orin** [comment]
> ![Image](https://github.com/user-attachments/assets/9e538ae7-cb91-4e2e-82dc-d638a6cf0470?raw=true)I also encountered this problem ![Image](https://github.com/user-attachments/assets/9e538ae7-cb91-4e2e-82dc-d638a6cf0470?raw=true) 我也遇到了这个问题

I also had the same problem, have you solved it?

**Comment by DDL08** [comment]
> I also had the same problem, have you solved it?

I've already forgotten.
