### ISSUE TITLE
TypeError: init() takes no arguments (1 given)

### ISSUE THREAD

**Issue by nsrauf** [SecureAuthCorp/impacket#754]
After the git pull i am receiving this error "TypeError: init() takes no arguments (1 given)" for all scripts. ./scriptname.py -h runs fine.

I cloned the repo from git and not installed through apt.

any suggestions?

**Comment by thomaslc66** [comment]
Yeah i have the same problem on almost all script, search for logger.init(options.ts) and erase options.ts or comment the all line

**Comment by asolino** [comment]
Guys.. If you have that error it means you cloned the repro but didn't install it. There was a change in the [logger init() method](https://github.com/SecureAuthCorp/impacket/commit/5a0edb3a36a5c7a5b5c12c1e545de70f2e101bcb#diff-caeb4f558148cc3d4725b39df2503589) so in order to use all the scripts you need to update and install the library to its latest commit.

**Comment by nsrauf** [comment]
Thanks @asolino !! It worked!

In the past i was cloning the repo and using it. With this update cloning and pip install . solved the issue.

Thanks!

**Comment by asolino** [comment]
Closing this one.
